import {
  Activity,
  BarChart3,
  Bell,
  Bot,
  CheckCircle,
  ChevronLeft,
  ChevronRight,
  Clipboard,
  Copy,
  Download,
  Edit,
  ExternalLink,
  Eye,
  FileText,
  Globe,
  Home,
  LayoutDashboard,
  Link2,
  LogOut,
  Menu,
  Moon,
  MoreHorizontal,
  Plus,
  RefreshCw,
  Settings,
  Share2,
  Shield,
  Sun,
  Trash2,
  TrendingUp,
  Upload,
  User,
  Users,
  X,
  Zap,
  MapPin,
  PieChart,
  Globe2,
  Target,
  Rocket,
  Sparkles,
  Gauge,
  Headphones,
  Mail,
  Send,
  Check,
  AlertCircle,
  AlertTriangle,
  Info,
  Power,
  PowerOff,
  Search,
  Filter,
  Clock,
  Monitor,
  Smartphone,
  Tablet,
  ArrowLeft,
  Key,
} from 'lucide-react'

export const Icons = {
  activity: Activity,
  bell: Bell,
  bot: Bot,
  checkCircle: CheckCircle,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  clipboard: Clipboard,
  copy: Copy,
  dashboard: LayoutDashboard,
  download: Download,
  edit: Edit,
  externalLink: ExternalLink,
  eye: Eye,
  fileText: FileText,
  globe: Globe,
  home: Home,
  link: Link2,
  logout: LogOut,
  menu: Menu,
  moon: Moon,
  moreHorizontal: MoreHorizontal,
  plus: Plus,
  refresh: RefreshCw,
  settings: Settings,
  share: Share2,
  shield: Shield,
  sun: Sun,
  trash: Trash2,
  trendingUp: TrendingUp,
  upload: Upload,
  user: User,
  users: Users,
  x: X,
  zap: Zap,
  mapPin: MapPin,
  barChart: BarChart3,
  pieChart: PieChart,
  globe2: Globe2,
  target: Target,
  rocket: Rocket,
  sparkles: Sparkles,
  gauge: Gauge,
  headphones: Headphones,
  mail: Mail,
  send: Send,
  check: Check,
  alertCircle: AlertCircle,
  alertTriangle: AlertTriangle,
  info: Info,
  power: Power,
  powerOff: PowerOff,
  search: Search,
  filter: Filter,
  clock: Clock,
  monitor: Monitor,
  smartphone: Smartphone,
  tablet: Tablet,
  arrowLeft: ArrowLeft,
  key: Key,
}

export type IconName = keyof typeof Icons